name: Build Android Debug APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v4
        with:
          flutter-version: '3.27.3'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build Debug APK
        run: flutter build apk --debug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
          compression-level: 0 # APK đã được nén rồi
          retention-days: 5

      - name: Create Debug Build
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-debug.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: debug-v${{ github.run_number }}
          name: Debug Build v${{ github.run_number }}
          body: |
            Debug Build:
            - Branch: ${{ github.ref }}
            - Commit: ${{ github.sha }}
            - Build number: ${{ github.run_number }}
          prerelease: true 